# Generated by Django 4.0.9 on 2023-02-06 12:38

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0005_alter_sede_options_advogados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('orgao', models.CharField(max_length=150, verbose_name='Expedido por')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('C', 'Casado'), ('D', 'Divorciado'), ('S', 'Solteiro')], max_length=1)),
                ('naturalidade', models.CharField(blank=True, max_length=255, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(blank=True, max_length=255, verbose_name='Nacionalidade')),
                ('ocupacao', models.CharField(blank=True, max_length=255, verbose_name='Ocupação')),
                ('mae', models.CharField(blank=True, max_length=255, verbose_name='Mãe')),
                ('pai', models.CharField(blank=True, max_length=255, verbose_name='Pai')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('tipo_contato', models.CharField(choices=[('C', 'Cônjuge'), ('V', 'Vizinho'), ('M', 'Mãe'), ('P', 'Pai'), ('O', 'Outro')], max_length=1)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('nome_contato', models.CharField(blank=True, max_length=255, verbose_name='Nome Contato')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=25, verbose_name='Estado')),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero_residencia', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento_endereco', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Risco', 'Risco')], max_length=6, verbose_name='Tipo de contrato')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação')),
                ('foro_acao', models.CharField(default='Teixeira de Freitas - BA', max_length=255)),
                ('foro_execucao', models.CharField(default='Teixeira de Freitas - BA', max_length=255)),
                ('valor', models.CharField(default=0, max_length=25)),
                ('taxa', models.CharField(default=0, max_length=25, verbose_name='Taxa Escritório')),
                ('honorario', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('multa', models.DecimalField(decimal_places=2, default=20, max_digits=8)),
                ('mora', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('processo', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('advogados', models.ManyToManyField(default=1, to='config.advogados')),
                ('clientes', models.ManyToManyField(to='core.clientes')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
