# Generated by Django 4.0.9 on 2023-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contratos_taxa_alter_contratos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='foro_acao',
            field=models.CharField(default='Teixeira de Freitas - BA', max_length=255, verbose_name='Foro da Ação'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='foro_execucao',
            field=models.CharField(default='Teixeira de Freitas - BA', max_length=255, verbose_name='Foro da Execução'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='honorario',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='mora',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='taxa',
            field=models.CharField(blank=True, max_length=25, verbose_name='Taxa Escritório'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
