# Generated by Django 4.0.9 on 2023-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_sede_options_advogados'),
        ('core', '0003_alter_contratos_foro_acao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='advogados',
            field=models.ManyToManyField(blank=True, default=1, to='config.advogados'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='clientes',
            field=models.ManyToManyField(blank=True, to='core.clientes'),
        ),
    ]
