# Generated by Django 4.0.9 on 2023-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contratos_advogados_alter_contratos_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('R', 'Risco')], max_length=1, verbose_name='Tipo de contrato'),
        ),
    ]
