# Generated by Django 4.0.9 on 2023-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_sede_options_advogados'),
        ('core', '0005_alter_contratos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='advogados',
            field=models.ManyToManyField(blank=True, to='config.advogados'),
        ),
    ]
