# Generated by Django 4.0.9 on 2023-02-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contratos_advogados'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='parcelas',
            field=models.IntegerField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='tipo_pagamento',
            field=models.CharField(choices=[('V', 'À vista'), ('P', 'Parcelado')], default=1, max_length=1, verbose_name='Tipo de pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_entrada',
            field=models.CharField(blank=True, max_length=25, verbose_name='Entrada'),
        ),
    ]
