# Generated by Django 4.0.9 on 2023-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contratos_parcelas_contratos_tipo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='parcelas',
            field=models.IntegerField(null=True),
        ),
    ]
