# Generated by Django 4.0.9 on 2023-02-05 23:39

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
    ]
