# Generated by Django 4.0.9 on 2023-02-06 00:03

import cnpj_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_sede_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='cnpj',
            field=cnpj_field.models.CNPJField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
    ]
