# Generated by Django 4.0.9 on 2023-02-06 00:36

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0004_alter_sede_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sede'},
        ),
        migrations.CreateModel(
            name='Advogados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('oab', models.CharField(max_length=15, verbose_name='OAB')),
                ('uf_oab', models.CharField(max_length=2, verbose_name='UF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('C', 'Casado'), ('D', 'Divorciado'), ('S', 'Solteiro')], max_length=1)),
                ('nacionalidade', models.CharField(blank=True, max_length=255, verbose_name='Nacionalidade')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=25, verbose_name='Estado')),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero_residencia', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento_endereco', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
            },
        ),
    ]
